"""
export_utils.py

Export the final generated case study (with evidence) into a
downloadable Markdown or plain-text document.

Consumes the exact final schema produced by references.py:

    {
        "company_name": "zerodha",
        "case_study": {
            "Background": {
                "content": "...",
                "evidence": [
                    {
                        "chunk_id": "...",
                        "source_id": "...",
                        "source_name": "...",
                        "source_type": "...",
                        "snippet": "..."
                    },
                    ...
                ],
                "confidence": "High" | "Medium" | "Low" | "Weak Evidence"
            },
            ...
        }
    }

Nothing here renames or restructures that schema. It only reads it.
"""

import json
from pathlib import Path
from typing import Dict, Tuple


# ==========================================================
# Section order (matches the generator / references output)
# ==========================================================

SECTION_ORDER = [
    "Background",
    "Challenge",
    "Strategy",
    "Execution",
    "Results",
    "Learning",
]


# ==========================================================
# Helpers
# ==========================================================

def _ordered_sections(case_study: Dict) -> list:
    """
    Return the section names in canonical order, followed by any
    extra sections that might exist but are not in SECTION_ORDER
    (defensive: never silently drop a section).
    """
    ordered = [name for name in SECTION_ORDER if name in case_study]
    extra = [name for name in case_study if name not in SECTION_ORDER]
    return ordered + extra


# ==========================================================
# Markdown export
# ==========================================================

def build_markdown(final_case_study: Dict) -> str:
    """
    Build a Markdown string for the whole case study, including
    each section's content, confidence label, and evidence snippets.
    """
    company_name = final_case_study.get("company_name", "Unknown Company")
    case_study = final_case_study.get("case_study", {})

    lines = []
    lines.append(f"# Business Case Study: {company_name.title()}")
    lines.append("")
    lines.append(
        "_Generated by the AI-Powered Business Case Study Generator. "
        "Every section is backed by source evidence with a confidence rating._"
    )
    lines.append("")

    if not case_study:
        lines.append("No case study sections are available.")
        return "\n".join(lines)

    for section_name in _ordered_sections(case_study):
        section = case_study.get(section_name, {})
        content = section.get("content", "").strip()
        confidence = section.get("confidence", "Unknown")
        evidence = section.get("evidence", []) or []

        lines.append(f"## {section_name}")
        lines.append("")
        lines.append(f"**Confidence:** {confidence}")
        lines.append("")
        lines.append(content if content else "_No generated content available._")
        lines.append("")

        lines.append("### Evidence")
        if not evidence:
            lines.append("_No supporting evidence was found for this section._")
            lines.append("")
        else:
            for index, item in enumerate(evidence, start=1):
                source_name = item.get("source_name", "Unknown source")
                chunk_id = item.get("chunk_id", "N/A")
                source_type = item.get("source_type", "N/A")
                snippet = item.get("snippet", "").strip()

                lines.append(
                    f"{index}. **{source_name}** "
                    f"(`{chunk_id}`, type: {source_type})"
                )
                lines.append(f"   > {snippet}")
                lines.append("")

        lines.append("---")
        lines.append("")

    return "\n".join(lines).strip() + "\n"


# ==========================================================
# Plain-text export
# ==========================================================

def build_plain_text(final_case_study: Dict) -> str:
    """
    Build a plain-text version of the case study (no Markdown syntax),
    useful for pasting into documents that do not render Markdown.
    """
    company_name = final_case_study.get("company_name", "Unknown Company")
    case_study = final_case_study.get("case_study", {})

    line = "=" * 70
    lines = []
    lines.append(line)
    lines.append(f"BUSINESS CASE STUDY: {company_name.upper()}")
    lines.append(line)
    lines.append("")

    if not case_study:
        lines.append("No case study sections are available.")
        return "\n".join(lines)

    for section_name in _ordered_sections(case_study):
        section = case_study.get(section_name, {})
        content = section.get("content", "").strip()
        confidence = section.get("confidence", "Unknown")
        evidence = section.get("evidence", []) or []

        lines.append(section_name.upper())
        lines.append("-" * len(section_name))
        lines.append(f"Confidence: {confidence}")
        lines.append("")
        lines.append(content if content else "No generated content available.")
        lines.append("")
        lines.append("Evidence:")

        if not evidence:
            lines.append("  - No supporting evidence was found for this section.")
        else:
            for index, item in enumerate(evidence, start=1):
                source_name = item.get("source_name", "Unknown source")
                chunk_id = item.get("chunk_id", "N/A")
                snippet = item.get("snippet", "").strip()
                lines.append(f"  {index}. {source_name} ({chunk_id})")
                lines.append(f"     {snippet}")

        lines.append("")
        lines.append(line)
        lines.append("")

    return "\n".join(lines).strip() + "\n"


# ==========================================================
# Public export entry point
# ==========================================================

def export_case_study(
    final_case_study: Dict,
    fmt: str = "md",
) -> Tuple[str, str]:
    """
    Return (filename, content) for the requested format.

    fmt: "md"  -> Markdown
         "txt" -> plain text

    The filename uses the company name, e.g. "zerodha_case_study.md".
    """
    company_name = final_case_study.get("company_name", "case_study")
    safe_name = company_name.lower().replace(" ", "_")

    fmt = (fmt or "md").lower()

    if fmt == "txt":
        return f"{safe_name}_case_study.txt", build_plain_text(final_case_study)

    # default to markdown
    return f"{safe_name}_case_study.md", build_markdown(final_case_study)


def save_export(
    final_case_study: Dict,
    fmt: str = "md",
) -> Path:
    """
    Write the exported case study to outputs/case_studies/ and
    return the path. Used for CLI testing; the Streamlit app uses
    export_case_study() with a download button instead.
    """
    from src.config import CASE_STUDIES_DIR

    CASE_STUDIES_DIR.mkdir(parents=True, exist_ok=True)
    filename, content = export_case_study(final_case_study, fmt=fmt)
    output_path = CASE_STUDIES_DIR / filename

    with open(output_path, "w", encoding="utf-8") as file:
        file.write(content)

    return output_path


# ==========================================================
# Manual test
# ==========================================================

if __name__ == "__main__":
    from src.config import CASE_STUDIES_DIR

    company = "zerodha"
    json_path = (
        CASE_STUDIES_DIR / f"{company}_case_study_with_evidence.json"
    )

    if not json_path.exists():
        print(f"No case study JSON found at: {json_path}")
        print("Run the pipeline first (references.py) to generate it.")
    else:
        with open(json_path, "r", encoding="utf-8") as file:
            final = json.load(file)

        md_path = save_export(final, fmt="md")
        txt_path = save_export(final, fmt="txt")

        print(f"Markdown export saved to: {md_path}")
        print(f"Plain-text export saved to: {txt_path}")
